#pragma once

typedef enum props_e {
	Prop_SputSput = 0x113,
	Prop_CheatoPage_Real = 0x136,
	Prop_CUSTOM_MOVE_ITEM = 0x187,
	Prop_Blue_Eggs = 0x1C8,
	Prop_Fire_Eggs = 0x1C9,
	Prop_Ice_Eggs = 0x1CA,
	Prop_Grenade_Eggs = 0x1CB,
	Prop_Clockwork_Eggs = 0x1CC,
	Prop_Gold_Eggs = 0x1CD,
	Prop_Red_Feather = 0x1CE,
	Prop_Gold_Feather = 0x1CF,

	Prop_Note = 0x1D7,
	Prop_Treble_Clef = 0x1D8,
	Prop_EggNest = 0x1E9,
	//Props with the Real label are the propids that are created by the spawner propids which are the ones that do not have real appended to them used by find functions
	Prop_Jinjo_Real = 0x1F4, 
	Prop_Jinjo = 0x1F5,
	Prop_Jiggy = 0x1F6,
	Prop_Honeycomb = 0x1F7,
	Prop_Glowbo = 0x1F8,
	Prop_CheatoPage = 0x201,
	Prop_BeeHive = 0x211,
	//Mega Glowbo is the only prop that shares the Propid with the spawned version
	Prop_MegaGlowbo = 0x21B,
	Prop_Jiggy_Real = 0x21F,
	Prop_Honeycomb_Real = 0x220,
	Prop_Honey = 0x229,
	Prop_Doubloon = 0x29D,
	Prop_JadeTotem = 0x2B3,
	Prop_Prox_Eggs = 0x2B8,
	Prop_Ticket_Real = 0x3C6,
	Prop_FeatherNest = 0x4A6,
	Prop_BoggyFish = 0x4BA,
	Prop_Doubloon_Real = 0x4E5,
	Prop_Ticket = 0x4E6,
} PropId;