//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TooieRando.rc
//
#define IDR_MANIFEST                    1
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GEDECOMPRESSOR_DIALOG       102
#define IDD_OLE_PROPPAGE_SMALL          104
#define IDD_CHANGE_LENGTH               104
#define IDR_MAINFRAME                   128
#define IDD_LOGIC_CREATOR               132
#define IDD_LOGIC_TRACKER               136
#define IDD_LOGIC_VIEWER                138
#define IDC_BUTTON1                     1000
#define IDC_DECOMPRESSFILEBUTTON        1000
#define IDC_COMPRESSFILEBUTTON          1001
#define IDC_BUTTON6                     1001
#define IDC_REMOVE_REQUIRED_MOVE        1001
#define IDC_COMPRESSFILEBUTTONENCRYPTED 1002
#define IDC_ADD_DEPENDENT               1002
#define IDC_REMOVE_DEPENDENT            1003
#define IDC_ADD_REQUIRED_ITEM           1004
#define IDC_COMBO1                      1005
#define IDC_OFFSET_TYPELIST             1005
#define IDC_LOGICSELECTOR               1005
#define IDC_REQUIRED_MOVE_SELECTION     1005
#define IDC_LOGIC_SELECT                1005
#define IDC_BUTTON2                     1006
#define IDC_DECOMPRESSGAME              1006
#define IDC_DEPENDENT_GROUP_SELECT      1006
#define IDC_CHECK1                      1007
#define IDC_DECOMPRESSGAME2             1007
#define IDC_REQUIRED_ITEM_SELECTION     1007
#define IDC_EDIT1                       1008
#define IDC_EDITSHOWHEX                 1008
#define IDC_SEED_ENTRY                  1008
#define IDC_NUMOFFSET                   1008
#define IDC_REMOVE_REQUIRED_ITEM        1008
#define IDC_CHECK2                      1009
#define IDC_OFFSET_LOCATION             1009
#define IDC_CREATE_NEW_GROUP            1009
#define IDC_BUTTON3                     1010
#define IDC_DELETE_GROUP                1010
#define IDC_EDIT2                       1011
#define IDC_EDITSEARCH                  1011
#define IDC_START_ASSET_ADDRESS         1011
#define IDC_REQUIRED_ITEM_NUMBER        1011
#define IDC_GENTXT                      1012
#define IDC_OFFSET_INDEX                1012
#define IDC_CREATE_NEW_REQUIREMENT_SET  1012
#define IDC_LISTDECOMPRESSEDFILES       1013
#define IDC_EDIT5                       1013
#define IDC_END_ASSET_ADDRESS           1013
#define IDC_DELETE_REQUIREMENTSET       1013
#define IDC_PROGRESS                    1014
#define IDC_REQUIRED_KEY_SELECTION      1014
#define IDC_BUTTONCANCELLOAD            1015
#define IDC_REMOVE_REQUIRED_KEY         1015
#define IDC_EDITENCRYPTED               1016
#define IDC_MOVE_LOCATIONS_LIST         1016
#define IDC_BUTTONSAVEROM               1017
#define IDC_BUTTONSEARCH                1018
#define IDC_EDIT3                       1019
#define IDC_VARIABLE_EDIT               1019
#define IDC_OFF_SHIFT_START             1019
#define IDC_GROUP_NAME_EDIT_BOX         1019
#define IDC_FILENUMBERLABEL             1020
#define IDC_OriginalObject              1023
#define IDC_ReplaceObject               1024
#define IDC_ApplyObjectChange           1025
#define IDC_EXPORT_SETTINGS_BUTTON      1027
#define IDC_BUTTON4                     1028
#define IDC_SEED_LABEl                  1029
#define IDC_IMPORT_SETTINGS_BUTTON      1030
#define IDC_ConfirmExtension            1031
#define IDC_RADIO2                      1033
#define IDC_SELECT_LIST                 1034
#define IDC_OPTION_LIST                 1038
#define IDC_SELECT_ADD                  1039
#define IDC_SELECT_REMOVE               1040
#define IDC_APPLY_OFFSET                1041
#define IDC_OFFSET_TARGET               1042
#define IDC_OFF_SHIFT_AMOUNT            1043
#define IDC_OFF_SHIFT_BUTTON            1044
#define IDC_REMOVE_OFFSET               1045
#define IDC_UNGROUPED_LIST              1046
#define IDC_LOGIC_EDITOR_BUTTON         1047
#define IDC_LOGIC_GROUP_LIST            1047
#define IDC_LOGICSELECTORLABEL          1048
#define IDC_DEPENDENT_GROUP_LIST        1048
#define IDC_LOGIC_EDITOR_BUTTON2        1049
#define IDC_LOGIC_TRACKER_BUTTON        1049
#define IDC_OBJECT_IN_GROUP_LIST        1050
#define IDC_REQUIRED_MOVE_LIST          1051
#define IDC_REQUIRED_ITEM_LIST          1052
#define IDC_ADD_REQUIRED_MOVE           1053
#define IDC_LIST1                       1054
#define IDC_ADD_REQUIRED_KEY            1054
#define IDC_WORLDSOPENED                1054
#define IDC_LIST2                       1055
#define IDC_REQUIRED_KEY_LIST           1055
#define IDC_LOADLOGICFILEBUTTON         1056
#define IDC_SAVELOGICFILEBUTTON         1057
#define IDC_REQUIREMENT_SELECTOR        1058
#define IDC_REQUIREMENT_SET_EDITBOX     1059
#define IDC_REWARD_KEY                  1060
#define IDC_SEARCH_GROUPS_BOX           1061
#define IDC_SEARCH_GROUPED_BOX          1062
#define IDC_SEARCH_UNGROUPED_BOX        1063
#define IDC_LOGIC_CHECK                 1064
#define IDC_ASSOCIATEDWARP              1065
#define IDC_DEPENDENT_SHUFFLEGROUP      1066
#define IDC_SPECIAL_TAG                 1067
#define IDC_CHECK3                      1067
#define IDC_DEVMODE                     1068
#define IDC_AVAILABLE_CHECKS            1068
#define IDC_MARKED_CHECKS               1069
#define IDC_COLLECTED_MOVES             1070
#define IDC_LOGIC_FILE                  1071
#define IDC_DISPLAY_BOX                 1072
#define IDC_DRAW_DISPLAY_BUTTON         1073
#define IDC_BUTTON5                     1074

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1075
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
